services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - '6379:6379'