services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
        
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis/data

#  semantic_service:
#    image: semantic_service:latest
#    build:
#      context: .
#      dockerfile: semantic/Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "9000:9000"
#    environment:
#      DATABASE_URL: "postgresql://postgres:postgrespw@postgres:5432/fuc"